server:
  port: 8083
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/post-service?authSource=admin

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    tryItOutEnabled: true
    filter: true

app:
  services:
    profile:
      url: http://localhost:8081/profile