server:
  port: 8083
  servlet:
    context-path: /post

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/post-service?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: redispass
      timeout: 60000
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
  cloud:
    openfeign:
      cache:
        enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    tryItOutEnabled: true
    filter: true

app:
  services:
    profile:
      url: http://localhost:8081/profile
  topics:
    notification-delivery: notification-delivery