server:
  port: 8085
  servlet:
    context-path: /chat
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/chat-service?authSource=admin
      auto-index-creation: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    tryItOutEnabled: true
    filter: true

app:
  services:
    profile:
      url: http://localhost:8081/profile
    identity:
      url : http://localhost:8080/identity
